# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.23.1_1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.23.1_1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/marco/dev/homebrew/hid_controller

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/marco/dev/homebrew/hid_controller

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.23.1_1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.23.1_1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/marco/dev/homebrew/hid_controller/CMakeFiles /Users/marco/dev/homebrew/hid_controller//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/marco/dev/homebrew/hid_controller/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pico-hid-mvs

# Build rule for target.
pico-hid-mvs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pico-hid-mvs
.PHONY : pico-hid-mvs

# fast build rule for target.
pico-hid-mvs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico-hid-mvs.dir/build.make CMakeFiles/pico-hid-mvs.dir/build
.PHONY : pico-hid-mvs/fast

#=============================================================================
# Target rules for targets named ELF2UF2Build

# Build rule for target.
ELF2UF2Build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ELF2UF2Build
.PHONY : ELF2UF2Build

# fast build rule for target.
ELF2UF2Build/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ELF2UF2Build.dir/build.make CMakeFiles/ELF2UF2Build.dir/build
.PHONY : ELF2UF2Build/fast

#=============================================================================
# Target rules for targets named bs2_default

# Build rule for target.
bs2_default: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bs2_default
.PHONY : bs2_default

# fast build rule for target.
bs2_default/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default.dir/build.make pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default.dir/build
.PHONY : bs2_default/fast

#=============================================================================
# Target rules for targets named bs2_default_bin

# Build rule for target.
bs2_default_bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bs2_default_bin
.PHONY : bs2_default_bin

# fast build rule for target.
bs2_default_bin/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_bin.dir/build.make pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_bin.dir/build
.PHONY : bs2_default_bin/fast

#=============================================================================
# Target rules for targets named bs2_default_padded_checksummed_asm

# Build rule for target.
bs2_default_padded_checksummed_asm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bs2_default_padded_checksummed_asm
.PHONY : bs2_default_padded_checksummed_asm

# fast build rule for target.
bs2_default_padded_checksummed_asm/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_padded_checksummed_asm.dir/build.make pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_padded_checksummed_asm.dir/build
.PHONY : bs2_default_padded_checksummed_asm/fast

#=============================================================================
# Target rules for targets named cyw43_firmware_package

# Build rule for target.
cyw43_firmware_package: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cyw43_firmware_package
.PHONY : cyw43_firmware_package

# fast build rule for target.
cyw43_firmware_package/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk/src/rp2_common/cyw43_driver/CMakeFiles/cyw43_firmware_package.dir/build.make pico-sdk/src/rp2_common/cyw43_driver/CMakeFiles/cyw43_firmware_package.dir/build
.PHONY : cyw43_firmware_package/fast

#=============================================================================
# Target rules for targets named PioasmBuild

# Build rule for target.
PioasmBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PioasmBuild
.PHONY : PioasmBuild

# fast build rule for target.
PioasmBuild/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk/src/rp2_common/cyw43_driver/CMakeFiles/PioasmBuild.dir/build.make pico-sdk/src/rp2_common/cyw43_driver/CMakeFiles/PioasmBuild.dir/build
.PHONY : PioasmBuild/fast

#=============================================================================
# Target rules for targets named cyw43_driver_picow_cyw43_bus_pio_spi_pio_h

# Build rule for target.
cyw43_driver_picow_cyw43_bus_pio_spi_pio_h: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cyw43_driver_picow_cyw43_bus_pio_spi_pio_h
.PHONY : cyw43_driver_picow_cyw43_bus_pio_spi_pio_h

# fast build rule for target.
cyw43_driver_picow_cyw43_bus_pio_spi_pio_h/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk/src/rp2_common/cyw43_driver/CMakeFiles/cyw43_driver_picow_cyw43_bus_pio_spi_pio_h.dir/build.make pico-sdk/src/rp2_common/cyw43_driver/CMakeFiles/cyw43_driver_picow_cyw43_bus_pio_spi_pio_h.dir/build
.PHONY : cyw43_driver_picow_cyw43_bus_pio_spi_pio_h/fast

src/board_output.obj: src/board_output.c.obj
.PHONY : src/board_output.obj

# target to build an object file
src/board_output.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico-hid-mvs.dir/build.make CMakeFiles/pico-hid-mvs.dir/src/board_output.c.obj
.PHONY : src/board_output.c.obj

src/board_output.i: src/board_output.c.i
.PHONY : src/board_output.i

# target to preprocess a source file
src/board_output.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico-hid-mvs.dir/build.make CMakeFiles/pico-hid-mvs.dir/src/board_output.c.i
.PHONY : src/board_output.c.i

src/board_output.s: src/board_output.c.s
.PHONY : src/board_output.s

# target to generate assembly for a file
src/board_output.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico-hid-mvs.dir/build.make CMakeFiles/pico-hid-mvs.dir/src/board_output.c.s
.PHONY : src/board_output.c.s

src/hid_app.obj: src/hid_app.c.obj
.PHONY : src/hid_app.obj

# target to build an object file
src/hid_app.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico-hid-mvs.dir/build.make CMakeFiles/pico-hid-mvs.dir/src/hid_app.c.obj
.PHONY : src/hid_app.c.obj

src/hid_app.i: src/hid_app.c.i
.PHONY : src/hid_app.i

# target to preprocess a source file
src/hid_app.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico-hid-mvs.dir/build.make CMakeFiles/pico-hid-mvs.dir/src/hid_app.c.i
.PHONY : src/hid_app.c.i

src/hid_app.s: src/hid_app.c.s
.PHONY : src/hid_app.s

# target to generate assembly for a file
src/hid_app.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico-hid-mvs.dir/build.make CMakeFiles/pico-hid-mvs.dir/src/hid_app.c.s
.PHONY : src/hid_app.c.s

src/main.obj: src/main.c.obj
.PHONY : src/main.obj

# target to build an object file
src/main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico-hid-mvs.dir/build.make CMakeFiles/pico-hid-mvs.dir/src/main.c.obj
.PHONY : src/main.c.obj

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico-hid-mvs.dir/build.make CMakeFiles/pico-hid-mvs.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico-hid-mvs.dir/build.make CMakeFiles/pico-hid-mvs.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ELF2UF2Build"
	@echo "... PioasmBuild"
	@echo "... bs2_default_bin"
	@echo "... bs2_default_padded_checksummed_asm"
	@echo "... cyw43_driver_picow_cyw43_bus_pio_spi_pio_h"
	@echo "... cyw43_firmware_package"
	@echo "... bs2_default"
	@echo "... pico-hid-mvs"
	@echo "... src/board_output.obj"
	@echo "... src/board_output.i"
	@echo "... src/board_output.s"
	@echo "... src/hid_app.obj"
	@echo "... src/hid_app.i"
	@echo "... src/hid_app.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

